package mapping

type MetricInfo struct {
	Namespace     string
	DimensionName string
	Period        int64
	MetricDetails []MetricDetail
}

type MetricDetail struct {
	MetricName string
	Statistics string
}

var MetricsMap = map[string]MetricInfo{
	// https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html
	"ec2": {
		Namespace:     "AWS/EC2",
		DimensionName: "InstanceId",
		Period:        60,
		MetricDetails: []MetricDetail{
			{"CPUCreditBalance", "Average"},
			{"CPUCreditUsage", "Average"},
			{"CPUSurplusCreditBalance", "Average"},
			{"CPUSurplusCreditsCharged", "Average"},
			{"CPUUtilization", "Average"},
			{"DiskReadBytes", "Average"},
			{"DiskReadOps", "Average"},
			{"DiskWriteBytes", "Average"},
			{"DiskWriteOps", "Average"},
			{"NetworkIn", "Average"},
			{"NetworkOut", "Average"},
			{"NetworkPacketsIn", "Average"},
			{"NetworkPacketsOut", "Average"},
			{"StatusCheckFailed", "Average"},
			{"StatusCheckFailed_Instance", "Average"},
			{"StatusCheckFailed_System", "Average"},
		},
	},
	// https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/AuroraUserGuide/Aurora.Monitoring.html
	"rds": {
		Namespace:     "AWS/RDS",
		DimensionName: "DBClusterIdentifier",
		Period:        60,
		MetricDetails: []MetricDetail{
			{"ActiveTransactions", "Average"},
			{"AuroraBinlogReplicaLag", "Average"},
			{"AuroraGlobalDBReplicatedWriteIO", "Average"},
			{"AuroraGlobalDBDataTransferBytes", "Average"},
			{"AuroraGlobalDBReplicationLag", "Average"},
			{"AuroraReplicaLag", "Average"},
			{"AuroraReplicaLagMaximum", "Average"},
			{"AuroraReplicaLagMinimum", "Average"},
			{"BacktrackChangeRecordsCreationRate", "Average"},
			{"BacktrackChangeRecordsStored", "Average"},
			{"BacktrackWindowActual", "Average"},
			{"BacktrackWindowAlert", "Average"},
			{"BackupRetentionPeriodStorageUsed", "Average"},
			{"BinLogDiskUsage", "Average"},
			{"BlockedTransactions", "Average"},
			{"BufferCacheHitRatio", "Average"},
			{"CommitLatency", "Average"},
			{"CommitThroughput", "Average"},
			{"CPUCreditBalance", "Average"},
			{"CPUCreditUsage", "Average"},
			{"CPUUtilization", "Average"},
			{"DatabaseConnections", "Average"},
			{"DDLLatency", "Average"},
			{"DDLThroughput", "Average"},
			{"Deadlocks", "Average"},
			{"DeleteLatency", "Average"},
			{"DeleteThroughput", "Average"},
			{"DMLLatency", "Average"},
			{"DMLThroughput", "Average"},
			{"EngineUptime", "Average"},
			{"FreeableMemory", "Average"},
			{"FreeLocalStorage", "Average"},
			{"InsertLatency", "Average"},
			{"InsertThroughput", "Average"},
			{"LoginFailures", "Average"},
			{"NetworkReceiveThroughput", "Average"},
			{"NetworkThroughput", "Average"},
			{"NetworkTransmitThroughput", "Average"},
			{"Queries", "Average"},
			{"ResultSetCacheHitRatio", "Average"},
			{"SelectLatency", "Average"},
			{"SelectThroughput", "Average"},
			{"SnapshotStorageUsed", "Average"},
			{"TotalBackupStorageBilled", "Average"},
			{"UpdateLatency", "Average"},
			{"UpdateThroughput", "Average"},
			{"VolumeBytesUsed", "Average"},
			{"VolumeReadIOPs", "Average"},
			{"VolumeWriteIOPs", "Average"},
		},
	},
	// https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html
	"ALB": {
		Namespace:     "AWS/ApplicationELB",
		DimensionName: "LoadBalancer",
		Period:        60,
		MetricDetails: []MetricDetail{
			{"ActiveConnectionCount", "Sum"},
			{"ClientTLSNegotiationErrorCount", "Sum"},
			{"ConsumedLCUs", "Average"},
			{"HTTP_Fixed_Response_Count", "Sum"},
			{"HTTP_Redirect_Count", "Sum"},
			{"HTTP_Redirect_Url_Limit_Exceeded_Count", "Sum"},
			{"HTTPCode_ELB_3XX_Count", "Sum"},
			{"HTTPCode_ELB_4XX_Count", "Sum"},
			{"HTTPCode_ELB_5XX_Count", "Sum"},
			{"HTTPCode_ELB_500_Count", "Sum"},
			{"HTTPCode_ELB_502_Count", "Sum"},
			{"HTTPCode_ELB_503_Count", "Sum"},
			{"HTTPCode_ELB_504_Count", "Sum"},
			{"IPv6ProcessedBytes", "Sum"},
			{"IPv6RequestCount", "Sum"},
			{"NewConnectionCount", "Sum"},
			{"ProcessedBytes", "Sum"},
			{"RejectedConnectionCount", "Sum"},
			{"RequestCount", "Sum"},
			{"RuleEvaluations", "Sum"},
			{"HTTPCode_Target_2XX_Count", "Sum"},
			{"HTTPCode_Target_3XX_Count", "Sum"},
			{"HTTPCode_Target_4XX_Count", "Sum"},
			{"HTTPCode_Target_5XX_Count", "Sum"},
			{"NonStickyRequestCount", "Sum"},
			{"RequestCountPerTarget", "Sum"},
			{"TargetConnectionErrorCount", "Sum"},
			{"TargetResponseTime", "Average"},
			{"TargetTLSNegotiationErrorCount", "Sum"},
		},
	},
	// https://docs.aws.amazon.com/ja_jp/AmazonElastiCache/latest/red-ug/CacheMetrics.HostLevel.html
	"ElastiCache": {
		Namespace:     "AWS/ElastiCache",
		DimensionName: "CacheClusterId",
		Period:        60,
		MetricDetails: []MetricDetail{
			{"CPUUtilization", "Average"},
			{"FreeableMemory", "Average"},
			{"NetworkBytesIn", "Average"},
			{"NetworkBytesOut", "Average"},
			{"NetworkPacketsIn", "Average"},
			{"NetworkPacketsOut", "Average"},
			{"SwapUsage", "Average"},
			// https://docs.aws.amazon.com/ja_jp/AmazonElastiCache/latest/red-ug/CacheMetrics.Redis.html
			{"ActiveDefragHits", "Average"},
			{"BytesUsedForCache", "Average"},
			{"CacheHits", "Average"},
			{"CacheMisses", "Average"},
			{"CurrConnections", "Average"},
			{"EngineCPUUtilization", "Average"},
			{"Evictions", "Average"},
			{"NewConnections", "Average"},
			{"Reclaimed", "Average"},
			{"ReplicationBytes", "Average"},
			{"ReplicationLag", "Average"},
			{"SaveInProgress", "Average"},
			{"CurrItems", "Average"},
			{"GetTypeCmds", "Average"},
			{"HashBasedCmds", "Average"},
			{"HyperLogLogBasedCmds", "Average"},
			{"KeyBasedCmds", "Average"},
			{"ListBasedCmds", "Average"},
			{"SetBasedCmds", "Average"},
			{"SetTypeCmds", "Average"},
			{"SortedSetBasedCmds", "Average"},
			{"StringBasedCmds", "Average"},
			{"StreamBasedCmds", "Average"},
		},
	},
}
